# # # # # # # # #
# MANGO CONFIG  #
# # # # # # # # #

# Main config file. Sources ALL THE FILES! HAHAHA!
source=/home/vallu/.config/mango/mango_modules/exec.conf
source=/home/vallu/.config/mango/mango_modules/env.conf
source=/home/vallu/.config/mango/mango_modules/windows.conf
source=/home/vallu/.config/mango/mango_modules/animations.conf
source=/home/vallu/.config/mango/mango_modules/layout_settings.conf
source=/home/vallu/.config/mango/mango_modules/misc.conf
source=/home/vallu/.config/mango/mango_modules/input.conf
source=/home/vallu/.config/mango/mango_modules/appearance.conf
source=/home/vallu/.config/mango/mango_modules/keybinds.conf
source=/home/vallu/.config/mango/mango_modules/rules.conf

# Dank Material Shell
# source=~/.config/mango/dms/colors.conf
# source=~/.config/mango/dms/layout.conf
# source=~/.config/mango/dms/outputs.conf
# 
# source=./dms/cursor.conf
