# # # # # # # # # # #
# KEYBOARD SETTINGS #
# # # # # # # # # # #

repeat_rate=50
repeat_delay=250
numlockon=1
xkb_rules_layout=us
xkb_rules_variant=altgr-intl


# # # # # # #
# TRACKPAD  #
# # # # # # #
# (needs relogin to apply)

disable_trackpad=1
tap_to_click=1
tap_and_drag=1
drag_lock=1
trackpad_natural_scrolling=1
trackpad_accel_speed=0.4
disable_while_typing=1
left_handed=0
middle_button_emulation=1
swipe_min_threshold=1
accel_profile=1
accel_speed=3.0
click_method=1


# # # # # # # # # #
# MOUSE SETTINGS  #
# # # # # # # # # #
# (needs relogin to apply)

mouse_natural_scrolling=0
