# # # # # # # # # # # # # # #
# SCROLLER LAYOUT SETTINGS  #
# # # # # # # # # # # # # # #
scroller_structs=20
scroller_default_proportion=0.8
scroller_focus_center=1
scroller_prefer_center=1
edge_scroller_pointer_focus=1
scroller_default_proportion_single=1.0
scroller_proportion_preset=0.5,0.8,1.0


# # # # # # # # # # # # # # # # #
# MASTER-STACK LAYOUT SETTINGS  #
# # # # # # # # # # # # # # # # #
new_is_master=1
default_mfact=0.55
default_nmaster=1
smartgaps=0


# # # # # # # # # # #
# OVERVIEW SETTINGS #
# # # # # # # # # # #
hotarea_size=10
enable_hotarea=0
ov_tab_mode=0
overviewgappi=5
overviewgappo=30


# # # # # # # # # #
# LAYOUT SUPPORT  #
# # # # # # # # # #
tagrule=id:1,layout_name:right_tile
tagrule=id:2,layout_name:right_tile
tagrule=id:3,layout_name:right_tile
tagrule=id:4,layout_name:right_tile
tagrule=id:5,layout_name:right_tile
tagrule=id:6,layout_name:right_tile
tagrule=id:7,layout_name:right_tile
tagrule=id:8,layout_name:right_tile
tagrule=id:9,layout_name:right_tile
