# # # # # # # #
# LAYER RULES #
# # # # # # # #

layerrule=animation_type_open:fade,layer_name:rofi
layerrule=animation_type_close:fade,layer_name:rofi
layerrule=noblur:0,layer_name:waybar
windowrule=appid:clipse,isfloating:1
# windowrule=appid:fastfetch_popup,isfloating:1
# windowrule=size 900 500,appid:fastfetch-popup,isfloating:1
