# Backtick for prefix key
unbind C-b
set -g prefix `
bind ` send-prefix

# Vim keybinds for window switching
# bind -r h previous-window
# bind -r l next-window
# bind -r left previous-window
# bind -r right next-window

# Start window and pane indices at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Remove delay after esc
set -sg escape-time 0
# Status bar message duration
set -g display-time 4000
# Scrollback buffer (seems too much, but idc)
set -g history-limit 50000
# Repeat time for prefix
set -g repeat-time 500
# vi keybinds in copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
# Actually good split keys
bind \\ split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
unbind '"'
unbind %
# Vim-style pane navigation
# unbind L
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
# Vim-style pane resizing (repeatable)
bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2
# Switch windows with alt+arrow
bind -n M-Left previous-window
bind -n M-Right next-window
# Pane navigation with ctrl+arrow
bind -n C-Left select-pane -L
bind -n C-Down select-pane -D
bind -n C-Up select-pane -U
bind -n C-Right select-pane -R
# Pane resizing with ctrl+shift+arrow
bind -n C-S-Left resize-pane -L 2
bind -n C-S-Down resize-pane -D 2
bind -n C-S-Up resize-pane -U 2
bind -n C-S-Right resize-pane -R 2

# === PLUGINS ===
set -g @plugin 'tmux-plugins/tmux-resurrect'
# === PLUGIN MANAGER ===
run '~/.tmux/plugins/tpm/tpm'

set -g status-style 'bg=#000000,fg=#CCCCCC,bold'
set -g status-justify left
set -g status-interval 1
set -g status-left-length 50
set -g status-right-length 120
set -g status-left "#[fg=#909090]#S #[fg=#505050]-> "
set -g status-right "#(~/bin/cpu_mem) \
#[fg=#505050]| #(~/bin/battery) \
#[fg=#505050]| #[fg=#CCCCCC]%d-%m-%y #[fg=#1090C0]%I:%M%p"
setw -g window-status-current-style 'fg=#00AA00'
setw -g window-status-current-format "#I:#W "
setw -g window-status-format "#I:#W "
