# Hoohoooooo! HYPRLAND!

###############
### SOURCES ###
###############

source = /home/vallu/.config/hypr/hyprlang_mods/env.conf
source = /home/vallu/.config/hypr/hyprlang_mods/vars.conf
source = /home/vallu/.config/hypr/hyprlang_mods/permissions.conf
source = /home/vallu/.config/hypr/hyprlang_mods/exec.conf
source = /home/vallu/.config/hypr/hyprlang_mods/rules.conf
source = /home/vallu/.config/hypr/hyprlang_mods/input.conf
source = /home/vallu/.config/hypr/hyprlang_mods/keybinds.conf
source = /home/vallu/.config/hypr/hyprlang_mods/monitors.conf
source = /home/vallu/.config/hypr/hyprlang_mods/render.conf
source = /home/vallu/.config/hypr/hyprlang_mods/animations.conf
source = /home/vallu/.config/hypr/hyprlang_mods/appearance.conf
source = /home/vallu/.config/hypr/hyprlang_mods/layouts.conf
source = /home/vallu/.config/hypr/hyprlang_mods/misc.conf
source = /home/vallu/.config/hypr/hyprlang_mods/quirks.conf
