#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.);

# exec-once = $terminal
exec-once = waybar -c ~/.config/waybar/config_top.jsonc -s ~/.config/waybar/style_top.css
exec-once = waybar -c ~/.config/waybar/config_bottom.jsonc -s ~/.config/waybar/style_bottom.css
# exec-once = caelestia shell -d
exec-once = hyprpaper
# exec-once = dunst
exec-once = mako
exec-once = hypridle
exec-once = hyprsunset
exec-once = clipse -listen

# Turn off Bluetooth at log on;
exec-once = bluetoothctl power off
exec-once = wpctl set-volume `pactl list short sinks | grep -ioE '[0-9]+\s+' | head -n 1` 0.1

# Hyprland Monitor Manager - Auto-manage displays and lid
# exec-once = hmonitor daemon

exec-once = ~/bin/batt_listener
