#############
### INPUT ###
#############

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =

    numlock_by_default = true
    repeat_delay = 250
    repeat_rate = 30
    sensitivity = 1.0
    accel_profile = flat

    follow_mouse = 1

    # sensitivity = 0 # -1.0 - 1.0, 0 means no modification.

    touchpad {
        natural_scroll = true
        disable_while_typing = true
        scroll_factor = 0.4
    }
}

# See https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more;
device {
    name = epic-mouse-v1
    sensitivity = -0.5
}

cursor {
    inactive_timeout = 90
    no_warps = false
    persistent_warps = false
    zoom_factor = 1.0
}
