#################
### VARIABLES ###
#################

# Programs;
$terminal = alacritty
$fileManager = nautilus
$menu_drun = rofi -show drun
$menu_run = rofi -show run
$menu_filebrowser = rofi -show filebrowser
$menu_recursivebrowser = rofi -show recursivebrowser
$menu_combi = rofi -show combi
