-- source files from lua/
require("lua.animations")
require("lua.appearance")
require("lua.env")
require("lua.exec")
require("lua.input")
require("lua.keybinds")
-- require("lua.keybinds_noctalia_v4")
require("lua.layouts")
require("lua.misc")
require("lua.monitors")
require("lua.permissions")
require("lua.plugins")
require("lua.quirks")
require("lua.render")
require("lua.rules")
require("lua.vars")
