-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-----------------
--- VARIABLES ---
-----------------

local terminal = "alacritty"
local fileManager = "nautilus"
local menu_drun = "rofi -show drun"
local menu_run = "rofi -show run"
local menu_filebrowser = "rofi -show filebrowser"
local menu_recursivebrowser = "rofi -show recursivebrowser"
local menu_combi = "rofi -show combi"
