# # # # # # # # # # # # # #
# ANIMATION CONFIGURATION #
# # # # # # # # # # # # # #
animations=1
layer_animations=1
animation_type_open=slide
animation_type_close=zoom
animation_fade_in=1
animation_fade_out=1
tag_animation_direction=0
zoom_initial_ratio=1.0
zoom_end_ratio=0.9
fadein_begin_opacity=0.0
fadeout_begin_opacity=0.8
animation_duration_move=500
animation_duration_open=400
animation_duration_tag=400
animation_duration_close=750
animation_duration_focus=400
# ORIGINAL BEZIER CURVES
# animation_curve_open=0.46,1.0,0.29,1
# animation_curve_move=0.46,1.0,0.29,1
# animation_curve_tag=0.46,1.0,0.29,1
# animation_curve_close=0.08,0.92,0,1
# animation_curve_focus=0.46,1.0,0.29,1
# animation_curve_opafadeout=0.5,0.5,0.5,0.5
# animation_curve_opafadein=0.46,1.0,0.29,1
##############################################
# CUSTOM BEZIER CURVES
animation_curve_open=0.2,0.8,0.2,1.0
animation_curve_move=0.2,0.8,0.2,1.0
animation_curve_tag=0.2,0.8,0.2,1.0
animation_curve_close=0.2,0.8,0.2,1.0
animation_curve_focus=0.2,0.8,0.2,1.0
animation_curve_opafadeout=0.2,0.8,0.2,1.0
animation_curve_opafadein=0.2,0.8,0.2,1.0
