# # # # # # # # # # # #
# APPEARANCE SETTINGS #
# # # # # # # # # # # #

border_radius=12
gappih=5
gappiv=5
gappoh=10
gappov=10
scratchpad_width_ratio=0.8
scratchpad_height_ratio=0.9
borderpx=4
rootcolor=0x201b14ff
bordercolor=0x444444ff
focuscolor=0xc9b890ff
maximizescreencolor=0x89aa61ff
urgentcolor=0xad401fff
scratchpadcolor=0x516c93ff
globalcolor=0xb153a7ff
overlaycolor=0x14a57cff

# # Window appearance
# border_radius=12
# borderpx=0
# focused_opacity=1.0
# unfocused_opacity=0.9
# 
# # Gaps
# gappih=5
# gappiv=5
# gappoh=5
# gappov=5
# 
# # Shadows (optional)
# shadows=1
# shadow_only_floating=1
# shadows_size=10
# shadows_blur=15
